import { Poseidon, Experimental, Encryption, PublicKey, Signature, Field, Sign } from 'snarkyjs';

import { UserState } from './UserState';

export const UserProof = Experimental.ZkProgram({
  publicInput: UserState,

  methods: {
    generateUserProof: {
      privateInputs: [PublicKey, Signature, Field, Field],

      method(
        userState: UserState,
        userPublicKey: PublicKey,
        userSignature: Signature,
        voteWeight: Field,
        userBalance: Field
      ) {
        // Check if voteWeight <= userBalance
        voteWeight.assertLessThanOrEqual(userBalance);

        // Check if userSignature is generated by userPrivateKey
        userSignature.verify(
          userPublicKey,
          [userState.electionID]
        );
      },
    },
  },
});
